# Generated by Django 5.2.6 on 2025-09-28 02:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='hunger',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='pet',
            name='last_hunger_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pet',
            name='appearance',
            field=models.CharField(default='baby_happy', max_length=20),
        ),
    ]
